name: Tender Report Generator
on:
  push:
    paths:
      - 'inputs/**'
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils
          
      - name: Install Python packages
        run: |
          pip install openai pytesseract pdf2image  # Uses latest OpenAI (v1.0+)
          
      - name: Run OCR and AI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/ocr.py
          python scripts/report.py  # Updated to new API
          
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: tender-report
          path: outputs/
