name: Tender Report Generator
on:
  push:
    paths:
      - 'inputs/**'  # Triggers when you add files to inputs/
  workflow_dispatch:  # Lets you manually run it

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          sudo apt-get install tesseract-ocr
          pip install pytesseract openai pdf2image
          
      - name: Run OCR and AI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/ocr.py
          python scripts/report.py
          
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: tender-report
          path: outputs/
